"""
TEACHER AI FEATURES — END-TO-END API TEST
Tests every backend endpoint that powers the teacher AI tools:

1.  Teacher login
2.  Dashboard
3.  My students / sections
4.  Homework library
5.  Create homework (shell)
6.  Patch questions
7.  Assign homework
8.  AI: Lesson Plan Creator      → POST /teacher/ai-tool  (tool=lessonplan)
9.  AI: Worksheet Generator      → POST /teacher/ai-tool  (tool=worksheet)
10. AI: Concept Explainer        → POST /teacher/ai-tool  (tool=concept)
11. AI: Presentation Creator     → POST /teacher/ai-tool  (tool=presentation)
12. AI: Grading Assistant        → POST /teacher/ai-tool  (tool=grading)
13. AI: Quiz / Question Generator→ POST /teacher/ai-generate-questions
14. Evaluate homework list       → GET  /teacher/evaluate/:id
15. Grade homework               → POST /homework/grade
16. Parent communication history → GET  /teacher/parent-communication
17. Send parent message          → POST /teacher/parent-communication/send
18. Interventions list           → GET  /teacher/interventions
19. Schedule                     → GET  /teacher/schedule
20. Homework preview (by ID)     → GET  /homework/:id
"""

import requests, json, sys, time

BASE = "http://localhost:8000"
TEACHER_EMAIL    = "john.doe@school.com"
TEACHER_PASSWORD = "teacher123"
STUDENT_PHONE    = "1111111111"   # Alice Johnson

PASS = "\033[92m✓\033[0m"
FAIL = "\033[91m✗\033[0m"
WARN = "\033[93m~\033[0m"

results = []

def check(name, resp, expected_status=200, key=None):
    ok = resp.status_code == expected_status
    data = None
    try:
        data = resp.json()
    except Exception:
        pass
    if ok and key:
        ok = key in (data or {}) or (isinstance(data, list) and len(data) >= 0)
    symbol = PASS if ok else FAIL
    print(f"  {symbol} {name}  [{resp.status_code}]")
    if not ok:
        print(f"       → {resp.text[:200]}")
    results.append((name, ok))
    return data if ok else None

def section(title):
    print(f"\n{'─'*60}")
    print(f"  {title}")
    print(f"{'─'*60}")

# ── 1. Login ─────────────────────────────────────────────────
section("1. Teacher Login")
r = requests.post(f"{BASE}/auth/login", json={
    "email": TEACHER_EMAIL, "password": TEACHER_PASSWORD, "role": "teacher"
})
login = check("POST /auth/login", r, key="access_token")
if not login:
    print("\n\033[91mCannot continue — login failed. Is the backend running?\033[0m")
    sys.exit(1)

token   = login["access_token"]
teacher_id = login["user_id"]
H = {"Authorization": f"Bearer {token}"}

# ── 2. Dashboard ─────────────────────────────────────────────
section("2. Dashboard")
r = requests.get(f"{BASE}/teacher/dashboard", headers=H)
check("GET /teacher/dashboard", r, key="teacher")

# ── 3. Students & Sections ───────────────────────────────────
section("3. Students & Sections")
r = requests.get(f"{BASE}/teacher/my-students", headers=H)
students_data = check("GET /teacher/my-students", r)
students = students_data or []

r = requests.get(f"{BASE}/teacher/my-sections", headers=H)
check("GET /teacher/my-sections", r)

# Get Alice's ID for later
alice = next((s for s in students if s.get("name") == "Alice Johnson"), None)
alice_id = alice["_id"] if alice else None
print(f"       Alice ID: {alice_id or 'NOT FOUND — run seed_data.py'}")

r = requests.get(f"{BASE}/teacher/students/by-class", headers=H, params={"class_name": "Grade 6-A"})
check("GET /teacher/students/by-class", r)

# ── 4. Homework Library ──────────────────────────────────────
section("4. Homework Library")
r = requests.get(f"{BASE}/homework/library", headers=H)
library = check("GET /homework/library", r)
print(f"       {len(library or [])} items in library")

# ── 5. Create Homework Shell ─────────────────────────────────
section("5. Create Homework")
r = requests.post(f"{BASE}/homework/create", headers=H, json={
    "title": "AI Feature Test Homework",
    "subject": "Mathematics",
    "assigned_to_class": "Grade 6-A",
    "description": "Auto-generated by test script",
    "submission_type": "online_quiz",
    "difficulty_level": "medium",
    "estimated_duration_minutes": 30,
    "due_date": "2026-05-01T23:59:59",
    "questions": [], "tags": ["test"], "assigned_students": [], "total_marks": 0,
})
hw_created = check("POST /homework/create", r, key="id")
hw_id = (hw_created or {}).get("id")
print(f"       Homework ID: {hw_id}")

# ── 6. Patch Questions ───────────────────────────────────────
section("6. Patch Questions")
if hw_id:
    r = requests.patch(f"{BASE}/homework/{hw_id}/questions", headers=H, json={
        "questions": [
            {"id": "q1", "question_number": 1, "total_questions": 2,
             "question_text": "What is 2+2?", "answer_type": "mcq",
             "options": [{"id":"a","text":"3","is_correct":False},{"id":"b","text":"4","is_correct":True}],
             "max_points": 2},
            {"id": "q2", "question_number": 2, "total_questions": 2,
             "question_text": "Explain addition.", "answer_type": "typed",
             "max_points": 3, "sample_answer": "Adding two numbers gives their sum."},
        ]
    })
    check("PATCH /homework/:id/questions", r, key="saved")
else:
    print(f"  {WARN} Skipped — no hw_id")

# ── 7. Assign Homework ───────────────────────────────────────
section("7. Assign Homework")
if hw_id and alice_id:
    r = requests.post(f"{BASE}/homework/assign", headers=H, json={
        "homework_id": hw_id, "student_ids": [alice_id], "due_date": "2026-05-01T23:59:59"
    })
    check("POST /homework/assign", r, key="assigned")
else:
    print(f"  {WARN} Skipped — missing hw_id or alice_id")

# ── 8. AI: Lesson Plan ───────────────────────────────────────
section("8. AI Tool — Lesson Plan Creator")
r = requests.post(f"{BASE}/teacher/ai-tool", headers=H, json={
    "tool": "lessonplan", "subject": "Mathematics", "topic": "Quadratic Equations", "grade": "Grade 8",
    "extra": {"duration": 45, "objectives": ["Solve quadratic equations"], "methods": ["Guided Practice"], "sections": ["Hook","Main Activity","Exit Ticket"]}
})
lp = check("POST /teacher/ai-tool (lessonplan)", r)
if lp:
    keys = list(lp.keys())
    print(f"       Response keys: {keys[:6]}")

# ── 9. AI: Worksheet ─────────────────────────────────────────
section("9. AI Tool — Worksheet Generator")
r = requests.post(f"{BASE}/teacher/ai-tool", headers=H, json={
    "tool": "worksheet", "subject": "Mathematics", "topic": "Linear Equations", "grade": "Grade 7",
    "extra": {"difficulty": "medium", "total_questions": 5, "question_types": ["mcq","short_answer"], "title": "Linear Equations Worksheet"}
})
ws = check("POST /teacher/ai-tool (worksheet)", r)
if ws:
    qs = ws.get("questions", [])
    print(f"       Questions returned: {len(qs)}")

# ── 10. AI: Concept Explainer ────────────────────────────────
section("10. AI Tool — Concept Explainer")
r = requests.post(f"{BASE}/teacher/ai-tool", headers=H, json={
    "tool": "concept", "subject": "Physics", "topic": "Photosynthesis", "grade": "Grade 6",
    "extra": {"style": "Analogy-based", "simplify": True, "include": ["analogy","key_points"]}
})
ce = check("POST /teacher/ai-tool (concept)", r)
if ce:
    print(f"       Has explanation: {'explanation' in ce or 'content' in ce}")

# ── 11. AI: Presentation Creator ────────────────────────────
section("11. AI Tool — Presentation Creator")
r = requests.post(f"{BASE}/teacher/ai-tool", headers=H, json={
    "tool": "presentation", "subject": "History", "topic": "World War II", "grade": "Grade 9",
    "extra": {"num_slides": 8, "duration_minutes": 30, "purpose": "lesson", "visual_style": "modern"}
})
pc = check("POST /teacher/ai-tool (presentation)", r)
if pc:
    slides = pc.get("slides", [])
    print(f"       Slides returned: {len(slides)}")

# ── 12. AI: Grading Assistant ────────────────────────────────
section("12. AI Tool — Grading Assistant")
r = requests.post(f"{BASE}/teacher/ai-tool", headers=H, json={
    "tool": "grading", "subject": "Mathematics", "topic": "Distributive Property",
    "grade": "Grade 7",
    "extra": {
        "question": "Explain how the distributive property works in 3(x+5)=30.",
        "student_response": "You multiply 3 by x and 3 by 5 to get 3x+15=30, then solve.",
        "total_marks": 3, "feedback_tone": "encouraging", "assistance_type": "feedback"
    }
})
ga = check("POST /teacher/ai-tool (grading)", r)
if ga:
    print(f"       Score: {ga.get('score','—')}/{ga.get('max_score','—')}")
    print(f"       Has feedback: {'feedback' in ga or 'feedbackDraft' in ga}")

# ── 13. AI: Question Generator ───────────────────────────────
section("13. AI Question Generator")
r = requests.post(f"{BASE}/teacher/ai-generate-questions", headers=H, json={
    "subject": "Mathematics", "topic": "Quadratic Equations",
    "grade": "Grade 8", "count": 3, "difficulty": "mixed", "question_types": ["mcq", "typed"]
})
qg = check("POST /teacher/ai-generate-questions", r)
if isinstance(qg, list):
    print(f"       Questions generated: {len(qg)}")
    for q in qg[:2]:
        print(f"         [{q.get('answer_type','?')}] {str(q.get('question_text',''))[:60]}...")

# ── 14. Evaluate Homework List ───────────────────────────────
section("14. Evaluate Homework (teacher view)")
if hw_id:
    # First submit as student so there's something to evaluate
    r_otp = requests.post(f"{BASE}/auth/otp/request", json={"phone": STUDENT_PHONE, "role": "student"})
    dev_otp = (r_otp.json() or {}).get("dev_otp")
    if dev_otp:
        r_ver = requests.post(f"{BASE}/auth/otp/verify", json={"phone": STUDENT_PHONE, "otp": dev_otp, "role": "student"})
        stu_token = (r_ver.json() or {}).get("access_token")
        SH = {"Authorization": f"Bearer {stu_token}"}
        requests.post(f"{BASE}/homework/submit", headers=SH, json={
            "homework_id": hw_id,
            "answers": [
                {"question_id": "q1", "answer": "b", "answer_type": "mcq"},
                {"question_id": "q2", "answer": "Adding two numbers gives their sum.", "answer_type": "typed"},
            ]
        })
        print(f"       Student submitted homework")
        time.sleep(2)

    r = requests.get(f"{BASE}/teacher/evaluate/{hw_id}", headers=H)
    ev = check("GET /teacher/evaluate/:id", r, key="homework")
    if ev:
        subs = ev.get("submissions", [])
        stats = ev.get("stats", {})
        print(f"       Submissions: {len(subs)} | Stats: {stats}")
else:
    print(f"  {WARN} Skipped — no hw_id")

# ── 15. Grade Homework ───────────────────────────────────────
section("15. Grade Homework")
if hw_id and alice_id:
    r = requests.post(f"{BASE}/homework/grade", headers=H, json={
        "homework_id": hw_id, "student_id": alice_id,
        "final_grade": "A", "final_score": 4.5,
        "teacher_feedback": "Great work! Clear understanding shown.",
        "question_overrides": [{"question_id": "q2", "points_awarded": 3, "comment": "Well explained"}],
        "publish": True
    })
    check("POST /homework/grade", r, key="status")
else:
    print(f"  {WARN} Skipped — missing hw_id or alice_id")

# ── 16. Parent Communication History ────────────────────────
section("16. Parent Communication")
r = requests.get(f"{BASE}/teacher/parent-communication", headers=H)
msgs = check("GET /teacher/parent-communication", r)
print(f"       Messages in history: {len(msgs or [])}")

# ── 17. Send Parent Message ──────────────────────────────────
section("17. Send Parent Message")
if alice_id:
    r = requests.post(f"{BASE}/teacher/parent-communication/send", headers=H,
                      params={"student_id": alice_id, "message": "Hi, Alice is doing great in class!"})
    check("POST /teacher/parent-communication/send", r, key="id")
else:
    print(f"  {WARN} Skipped — no alice_id")

# ── 18. Interventions ────────────────────────────────────────
section("18. Interventions")
r = requests.get(f"{BASE}/teacher/interventions", headers=H)
check("GET /teacher/interventions", r)

# ── 19. Schedule ─────────────────────────────────────────────
section("19. Schedule")
r = requests.get(f"{BASE}/teacher/schedule", headers=H)
check("GET /teacher/schedule", r)

# ── 20. Homework Preview ─────────────────────────────────────
section("20. Homework Preview (by ID)")
if hw_id:
    r = requests.get(f"{BASE}/homework/{hw_id}", headers=H)
    hw_detail = check("GET /homework/:id", r, key="title")
    if hw_detail:
        print(f"       Title: {hw_detail.get('title')} | Questions: {len(hw_detail.get('questions',[]))}")
else:
    print(f"  {WARN} Skipped — no hw_id")

# ── Summary ──────────────────────────────────────────────────
passed = sum(1 for _, ok in results if ok)
failed = sum(1 for _, ok in results if not ok)
total  = len(results)

print(f"\n{'═'*60}")
print(f"  RESULTS: {passed}/{total} passed  |  {failed} failed")
print(f"{'═'*60}")

if failed:
    print("\n  Failed checks:")
    for name, ok in results:
        if not ok:
            print(f"    {FAIL} {name}")
    sys.exit(1)
else:
    print("\n  \033[92mAll teacher AI feature endpoints verified ✓\033[0m\n")
